### ISSUE TITLE
Feature: rework application structure

### ISSUE THREAD

**Issue by msvaillant** [ISDStudentsInitiative/DaWay#6]
So, as considered - project should consist of different layers
For the beginning :
- UI levelm controllers. Raror pages, some Web specific staff
- Domain/Business level. Usually we create a class library (netstandard) per Services, Repositories, Entities - in the case of this project we will just use decouple from UI level, on Domain library we will use Feature-Folder Struct (so services, repos, model per feature)

[**Feature folder (Ru)**](https://habrahabr.ru/post/321392/)

[**Onion Architecture (En)**](https://social.technet.microsoft.com/wiki/contents/articles/36655.onion-architecture-in-asp-net-core-mvc.aspx)

**Comment by VolfsonAlexandr** [comment]
Возникло несколько вопросов:
Правильно ли я перевел и понял, что нужно создать 2 основные папки: 
1)в первой будет все, что касается веб-страниц и контроллеры
2)во второй - модели, репозитории, сервисы, и во второй папке будут подпапки, каждая из которых относится к отдельной feature?

**Comment by AleksMorozova** [comment]
Все правильно.

**Comment by VolfsonAlexandr** [comment]
Как лучше назвать эти папки? Какие из них заполнять файлами, которые уже имеются, а какие оставить пустыми?
Нужно будет сделать реализацию интерфейсов IViewLocationExpander и IControllerModelConvention? Где хранить файлы с их реализацией?

**Comment by AleksMorozova** [comment]
UI, Domain  как вариант, а внутренние по фичам.
Папки заполнять более логично когда будет разрабатываться фича, существующие файлы можно переместить потом. 
Реализации хранить с той фичей, где они нужны будут.

**Comment by msvaillant** [comment]
Serhii Matviienko, [22.01.18 21:48]
так, собственно
чего я хотел, чего я имел в виду
UI = InstaBotPrototype
Domin = InstaBotLibrary
у тебя вышло не то, это мой косяк
в instabotprototype - сделал годно, только domain переименуй пока в services. но в следствии недопонимания ты там сделал годное решение.

Serhii Matviienko, [22.01.18 21:50]
InstaBotLibrary - тут надо сделать следующее:
1. забери изменения из development, там много чего Дима закинул
2. замени структуру Models, Services, Repositories, etc на вариант feature-folder, то есть к примеру: Users -> UserRepository, UserModel, UserService и тд

Serhii Matviienko, [22.01.18 21:51]
внутри этих папок можно также выделить подпапки типа Abstractions и Realization, по желанию уже
