### ISSUE TITLE
Feature: Dapper for Domain class library

### ISSUE THREAD

**Issue by msvaillant** [ISDStudentsInitiative/DaWay#7]
Related to #5.

- Add Dapper to main business layer
- Creates Repositories according to the Diagram.

Example of such a negotiation:
http://techbrij.com/asp-net-core-postgresql-dapper-crud

**Comment by Dicrit** [comment]
Непонятно что именно тут требуется сделать. Как это связано с #5 и какая диаграмма упоминается?

**Comment by msvaillant** [comment]
Надо установить пакет даппера, а еще у вас вроде была диаграмма компонентов, где репозитории сервисы и тд
так вот. в соответствии с ней завести интерфесы и написать хоть несколько реализаций оных. собственно реализации включают в себя использование даппера

**Comment by Dicrit** [comment]
Это случаем не то, что было реализовано в ветке Repositiry?

**Comment by msvaillant** [comment]
Да, похоже на то
советую отмечать пулреквесты и вестки с работой над задачей, чтобы потом не решать вопросы "что сделано" и "что это вообще за задача"
